# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='经纪公司')),
            ],
            options={
                'verbose_name': '经纪公司',
                'verbose_name_plural': '经纪公司',
            },
        ),
        migrations.AddField(
            model_name='author',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='app01.MC'),
            preserve_default=False,
        ),
    ]
